---
title: "Garden data questions"
author: "Nurrospody"
date: "7/13/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Things to do once garden data is finished being collected, on 28Jul2020 at minimum**  
-Deal with missing values (some cardoon leaves had died, or grown new)  
-Get the average change (growth) of each indivual cardoon leaf, and each individual plant, per day  
-Get the average pansy flower growth of each individual flower per day  
-Is there any way to use ANOVA with this data as-is?  Or must commplementary n30 data be gathered until the 26th of August?  
-Visualze data in graphs that make sense (certain graphs wouldn't make sense)  

*Add more as you think of what to do, this list should grow overtime*

**Observations**  
New leaves seem to grow in as old ones die.  One of the leaves on Cardoon 2 is breaking off, and will be detatched in a few days.  A new leaf is currently growing on cardoon 2.  This happened before, too, with leaf 6.  (observation made on 14th july).  Would some 'average amount of leaves' be interesting, or 'how long leaves last' be interesting?
