---
title: "Week 6 Timecard"
author: "Nurrospody"
date: "5/4/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Monday** - 3 hours 27 minutes - set up timecard and README hyperlink, read quite a few pages into the chapter, generated a random distribution of 70n to work with and did a bunch of basic stats calculations!  Talked about seeds, tried to make sure everything had a definition appended to it.

**Tuesday** - 1 hours 53 minutes - finished chapter 4 part 3 report, worked with finding modes, changing data 'modes' (which is apparently different), learning some things about functions and floating values (and doubles, which are more accurate numbers than floating values), learned that for some reason 'numeric' data takes up more memory than 'interger' data (and also numbers in R are really big?)

**Wednesday** - 0 hours 11 minutes - Started part 4 of chapter 4 report, made files and updated README.

**Thursday** - 0 hours 0 minutes - work description

**Friday** - 0 hours 0 minutes - work description

**Saturday** - 0 hours 0 minutes - work description

**Sunday** - 0 hours 0 minutes - work description

End of week reflection.