---
title: "Week 3 Timelog"
author: "Nurrospody"
date: "4/13/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Monday** Aprx. 1 hours 32 minutes - Updated README for Report Repository, pushed and commited work from week 2 to github.  Continued work on Chapter 3.  
**Tuesday** Aprx. 2 hours 0 minutes - Continued work on Chapter 3.  Realized it's a 40+ page chapter and there's still 20 pages left.  Plan to delve into getting a .csv into R tomorrow.  
**Wednesday** Aprx. 1 hours 50 minutes -  Figured out how to load a .csv file into R!  Had to mess around with file paths.  Fixed my image that wasn't working in Chapter 2 Report.  Used cmd line.  
**Thursday** Aprx. 4 hours 30 minutes - Experimented more with my .csv, referred to the cran.r project for help a bit, reorganized my repositories into one repository with better directories, better README, and fixed file paths that changed; more progress on report.  
**Friday** Aprx. 0 hours 30 minutes -  ZOOM call with faculty, showed off progress so far.  Should maybe do a histogram with the timestamp data and see about converting it if neccesary, work with mean/median/mode, then move to a different dataset.  Spend most of the day working on other class, though.  
**Saturday** - N/A  
**Sundau** Aprx. hours minutes - For a change of pace, I read the Intro and Chapter 1 of my other required textbook: *Statistics Done Wrong* by Alex Reinhart and wrote about my engagement with the text!  

End of week discussion
