---
title: "Week 5 Timecard"
author: "Nurrospody"
date: "4/27/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Monday** - 3 hours 2 minutes - Typed up end of week reflection for week 4, finished up loop report, made new timecard.  Worked with the calculator function at the end of chapter 3`.  While reading the chapter review, I discovered that it didn't *actually* teach me how to use loops to print the same character-based message a hundred times . . . so I figured out how to do it before closing out of chapter 3.

**Tuesday** - 3 hours 12 minutes - Begun reading chapter 4 (descriptive statistics) and working on chapter 4 report!  Had to go onto an Rtools instalation adventure to use the xlsl package.

**Wednesday** - Aprx. ~2 hours - fixed an issue wehre I couldn't require(xlsx) because the file path didn't exist, or java wasn't installed, or the environment variable wasn't made in windows . . .

**Thursday** - 1 hours 37 minutes - created second report, continued work on chapter 4, figured out why images work the way they do in markdown (it's a hyperlink, but with no text--instead an ! image)

**Friday** - 15 minutes - typed up summary of the week's work and sent it to my sponsor! Also fixed some GitHut hyperlinks.

**Saturday** - 1 hours 0 minutes - I didn't have a .sav file to work with, so I made one!  Writing it was more difficult than reading it however; reading it wrote weird things to the file.

**Sunday** - 0 hours 0 minutes - work description

End of week reflection.
