---
title: "Week 10 Worklog"
author: "Nurrospody"
date: "6/1/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Monday** - Aprx. 47 minutes - Made new timelog; sent out an email to the acedemic deans about expanding the ILC? / post-quarter ILC changes; 
**So I'm not sure what happened, since I've been doing this the whole 2+ months that I've been working on this ILC so far, but for some reason trying to record my ILC time with a stopwatch has become stressful?  It's like R has become so integrated into my activities that I want to treat it like everything else I do: come to it, leave from it, ad come back.  Turning the timer on/off used to be totally naturall, but now it's difficult.  Maybe it has to do with the new work area: since I'm working in the living room now, and there's 3 distinct areas to be in the living room but I randomly change locations all the time.  
It's week 10 now, so it's not a big deal if I decide to change it since week 1 of summer will be 'new'.

**Tuesday** - Corresponded with dean email.

**Wednesday** - 2 1/2 to 3 hours - Wrote up a first draft for my Summer 2020 ILC, as that's due on Friday.
