---
title: "Week 4 Timelog"
author: "Nurrospody"
date: "4/20/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Reminder: Sunday work from Week 3 exists and was not discussed last ZOOM meeting.  Consider starting each week on Saturday?*

**Monday** - 0 hours 55 minutes - Downloaded the rest of my R book because I could only download 200 pages total and my book was about 250 pages long.  Made new timecard and discussed schedule statagies.  My internet wasn't working for a while today so my workflow got interrupted.

**Tuesday** - 4 hours 10 minutes - Read ahead into the logical statements and loop functions section. . . spent some time learning about how they worked from partner because they seemed a bit confusing, then tried making some loops and logical functions.  They're in their own report, "Logical Statements and Loops CH3"
Also looked into time formatting for getting means of Smallmad[,6], found something called chron but it wasn't information helpful for what I was doing.  Learned about modulus %% and how it returns the remainder of division.

**Wednesday** - 2 hours 7 minutes - My reports have inconsistant formatting and are difficult to read, so I decided to spend some time today improving them.  They're now split up into smaller chunks.  I also completed the Vocabulary list for CH3.

**Thursday** - 4 hours 5 minutes - Spent time making the Matrix and Madoka Data.frame report more legible; this (and the vector section) were the hardest to read. I found that rewording the reports was helpful because it engaged me with the material again (like a review?) and I recognized concepts better.  Also re-wrote the Logical Statements and Loops CH3 report, which was much easier after digesting the information for a day or two.  Updated the FULL Ch3 report, but decided I will not make both segmented reports and full reports for future chapters--it's so long that the scroll bar disappears in the R Code Editor, which is not good.  Updated the README and had to fix Github conflicts which resulted.

**Friday** - 0 hours 0 minutes - Other class' work.

**Saturday** - 0 hours 30 minutes - ZOOM Class meeting; cute variable names shouldn't be used since it's bad practice ;w; use new data sets every week if possible, make sure to look into new statistics stuff as well as R coding (so reading the stats book is a good thing to do each week).  Otherwise, did other class' work.

**Sunday** - 2 hours 57 minutes - Riley gave me a new dataset to work with--I got the *.csv* of his CTF performance from IntroSecCon.  But before I can make a function with it, I finished learning the other loop types so I don't have a bad time.  Repeat loop is chaotic and makes awful things happen.  Also learned about proper indent levels & whitespace for code legibility.  Found a github for my textbook https://github.com/Apress/learn-r-for-applied-statistics


This week I was successful in getting a lot of work done--I think it's the closest I've hit to my 15 hours a week goal, at 884 minutes of productive time (or 14 hours and 44 minutes).  
Wednesday was really rough for me--even though I only have 2 hours logged, those 2 hours stretched over 5 hours.  I had a really difficult time with getting distracted by other things.  But being frustrated by that, having moral and on-topic support in the form of my partner, and trying to make a plan earlier added up to me doing better the rest of the week: on Sunday, I worked for 3 hours, within 4 hours (I took about an hour inbetween to each dinner and water the garden) which feels substantially better.  
This is the second week that I spent a lot of time re-organizing my github; obviously I'll have to re-organize things as they come up, but I hope it doesn't take big chunks of time in the future again.  It's now week 5 and I'm still in chapter 3 . . . given I'm right at the end of chapter 3, once I finish that I'll be in Chapter 4 Descriptive Statistics--but it still has been pretty slow.  But, Chapter 4 being about Statistics should be good for me; when I read from my Stats Gone Wrong book last Sunday it was like reuiniting with an old friend (it's odd to me how much of this ILC has basically just been spent learning how to program . . . luckily that was part of the ILC description).  
The meeting felt weird this week . . . even though I kept having new things to share during the meeting it just felt less positively received than the previous weeks.  Maybe it's because we're getting later in the quarter and I haven't been able to skip ahead in the book to more exciting things or more stats related things; and while I'd *like* to do that, I have no programing language background, this is all really new to me and I can't *do* more exciting stats related things like I want to until I get more of a backbone in understanding basic things like functions and loops and how formatting code works.  I feel like there's this pressure to show off cool things but I'm really just still learning.
