---
title: "Week 19 Timecard"
author: "Nurrospody"
date: "8/14/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Learning Objectives this week** - resampling, non-parametric tests, more data stuff with server

**Total Time inclusive from 14AUG2020 to 20AUG2020** : 4 hour 45 minutes (updated 1253 Wed)  

**Friday** - 1 hour 17 minutes - reflecting on week, Wilcoxon signed rank test; got out old textbook to help remind myself on what this stuff was.

**Saturday** - 1 hour 8 minutes - Wilcoxon rank sum test (and X+Y signed rank test); Wilcoxon-Mann-Whitney Test.  Used a new dataset for the Wilcoxon-Mann-Whitney Test.  

**Sunday** - 43 minutes - Kruskal-Wallis Test, and how to interpret the results.  I looked in my old Triola statsbook; my current R-book; and help("kruskal.test") for information.  Incidentally my current R book was the least helpful . . . but it makes figuring out what to do easy, at least.

**Monday** - 33 minutes - Updated README, made new chapter report since the old one was starting to take a long time to knit.  Fixed broken links finally.  
Started looking into linear analysis (I thought there were more non-parametric tests to do in the book, but there weren't).  The book doesn't really explain anything so I'm instead using [this site](https://www.scribbr.com/statistics/simple-linear-regression/) as my reference, which is instead very helpful and complete.  Last time I used this site I used their dataset since I didn't have any good sets for t-tests and ANOVA, but I want to see if I can use my own data this time.  

**Tuesday** - 1 hour - Linear analysis report and interpretting the results.  

**Wednesday** -

**Thursday** - 


**Start of Week Comments**: This is week 9 but it should be more like . . . week 4 . . . given the amount of successful weeks I've had this summer.  I really don't know why it's been so hard since basically week 7 of my spring semester.  By impulse I want to say that I wish I'd taken the summer off but . . . I've been able to do some really good things because of the stuff I learned around week 4 and 5 of this quarter.  Interacting with the people in my server with my stats knowledge was really amazing.  I've had a new dataset from someone who worked hard to compile it for like a week and I have to do stuff with it . . . I've been too depressed to touch it but I really ought to use it once I can.  For now I need to do non-parametrics to finish my book, and look into my basic stats book from Stats 1-2 to refresh on when to use them.  I can look into resampling some other time.

**End of Week Comments**: