---
title: "Week 12 Worklog"
author: "Nurrospody"
date: "6/29/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Total Time from 29JUN2020 to XJUL2020** : 2 hour 43 minutes

**Monday** - 1 hours 10 minutes - Made new worklog; wrote up end comments for Week 11 worklog.  Decided to record data of: # of flowers on pansy plants 1-5 AND length of leaves on Cardoon plants 1-2.  Going out into the garden to record the data for the first time was pretty fun; I had to think about how to record the data.  At first I started making an Rmarkdown document, but I realized that I wouldn't be able to easily use the data if I recorded it that way.  Instead, I chose to make an excel workbook.  The workbook has 4 sheets, one for each type of data (live pansy, dead pansy, cardoon 1, cardoon 2), and each sheet has 6 columns: date, then plant or leaf 1-5.  For the cardoons I'm not actually keeping track of WHICH leaf is how long since it doesn't matter, but they still needed to all be in their own column.  I'll need to use Header=TRUE and specify the sheet number when I do something with my data practicum.  Updated README to contain a direct link to the xlsx file.

**Tuesday** - 33 minutes - Recorded data from plants; pansies seem to have many, very short lived flowers, which is weird . . . by seeing the numbers, I think I'll get an idea of how fast they come in and if I missed a dead flower or two.  For the cardoons, Cardoon 2 grew faster than Cardoon 1 today.  It also seems that even though I'm not doing it on purpose, I'm measuring the leaves in the same order as yesterday, so I actually do get to see how much each leaf grows per day.  The pot is heavy so I may not be able to do it, but I'm curious: if I turn the pot each day, will the growth be about equal for each, or is Cardoon 2 actually a speedier grower than Cardoon 1?

**Wednesday** - 30 minutes - Gathered data from garden; thought about how I should be coming up with the questions I want to ask with my data, so that I can figure out how to answer those questions.  I only have one chapter left of my book, and after that I'm on my own for what to learn.  What I think I'll do is find datasets that are out there already and use them to learn how to do whatever questions I want to answer; then I'll know how to do them once I actually have my n >= 30 days.  It'll take a while to get there, so I have a bit.  Then, if I decide to change some factors after the first data set is done--like if I turn the cardoon pot--would I be able to do ANOVA stuff with it after getting a second type of n >= 30 data?

**Thursday** - 30 minutes - Gathered data; input it into excel sheet; updated timecard thoughts.  I really ought to start making headway on book stuff; aside from random fourth of July prepartion explosions, everything's pretty much finally calmed down.

**Friday** - 

**Saturday** - 

**Sunday** - I almost always take Sunday off.

**End of Week Comments**:

 
