---
title: "Week 13 Worklog"
author: "Nurrospody"
date: "7/8/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Total Time inclusive from 6JUL2020 to 12JUL2020** : 1 hour 43 minutes

**Monday** - 12 minutes - collected data.  Our water wasn't working again, so we had people in and out with loud power tools all day.  After I collected data I was going to input everything and update my timecards, but honestly I was so stressed out I took a 90 minute walk instead.  Officially dedcided to start measuring the new leaves.

**Tuesday** - 11 minutes - collected data.  Water stuff still out of order.  Thought about how I'll need to compile a list of my 'questions to look into for using my data'.

**Wednesday** - 1 hour 21 minutes - collected data; updated timecards; input 6 days' data into excel sheets.  (It's supposed to be put in daily.)  Scanned in the papers that I've been recording data on in the garden, so that I have them to show off.

**Thursday** - 

**Friday** - 

**Saturday** -

**Sunday** - 

**End of Week Comments**: Because everything was so out of control I was sleeping for 10+ hours each night so waking up late, but I mid-week decided to fix that so that I have enough time to be productive.


 
