---
title: "Week 20 Timecard"
author: "Nurrospody"
date: "9/1/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Learning Objectives this week** - resampling, non-parametric tests, more data stuff with server

**Total Time inclusive from 1SEP2020 to end of goal** : 

This is the last week!  The goal this week is to do some resampling and get the linear regression plot made if I can.  I hurt my hand so working at the computer is kind of hard, so resampling is the biggest priority.  

**Tuesday** 30 minutes - Found sources about resampling; it's a lot different than I thought it would be!  So I got a headache pretty fast, oops.  

**Thursday** about an hour? - worked on the first part of the report and getting all the sources needed for the resampling.  got through the first intro part and what resampling is, then needed a break.  

**Friday** about 45 minutes fixing README to contain Rmd files for Richard's reference, since I only had md in the README.  