---
title: "SPECIAL CH4 - Further Investigation into High Kurtosis and Normality"
author: "Nurrospody"
date: "5/14/2020"
output:
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data can be perfectly normally distributed but with high levels of kurtosis.  High kurtosis means that much of the variation comes from outliers in the tails, rather than normal variation in the curve.
Is symmetry all data needs to be normal?  If a curve is not biased, but extremely steep, is it *actually* normally distributed data?

On rdocumentation.org, there is a page that [documents R functions that do normality tests](https://www.rdocumentation.org/packages/fBasics/versions/3011.87/topics/NormalityTests).  

If a normality test is ALSO a omnibus test, it can help mathematically solve tihs problem, since both skew AND kurtosis are involved in the calculations.  The source page I found does not list the "full" names of each test, but I found from other reading that the full name of the ```dagoTest``` D'Agostino normality test is "D'Agostino-Pearson *omnibus* test".  
If I want to test for normality with both skew and kurtosis involved, I'll have to more intimately look what all these normality tests do and what they use in their equations.  Alternately, I can test data with multiple tests, and note that different results represent the data that was or wasn't used in each equation.  (I must be careful to not fall into the trap of running data multiple times until I get a test that does tell me what I want).

After some browsing, my best resource seemed to be [an online pdf from NCSS Statistical Software](https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Normality_Tests.pdf) about different Normality equations.

It appears that the shapiro test is the highest regarded of the normality tests, being able to reliably test samples with up to n5000 (theoretically unlimited n).
I had mentioned not knowing what W was; it is roughly a measure of how straight a Q-Q plot of the same data will be.  So a value closer to 1 means a more straight Q-Q plot.



---
Many of these must be from packages I don't have installed yet, since they don't return any help() or ??x pages, but these two I can currently lookup.  
jarque.test {moments}  
shapiro.test {stats}  
---

To continue reading the CH4 reports, select a new section:  
[Part 5 of the Chapter 4 Reports](https://github.com/Nurrospody/SOURCE-Statistics-ILC/blob/master/Chapter%20Reports/CH4-part5.md)  
[Link to README to select any Chapter Report](https://github.com/Nurrospody/SOURCE-Statistics-ILC/blob/master/README.md)

